include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "lib/generated*.dart"
    - "lib/model/*.dart"

linter:
  rules:
    - sort_constructors_first
    - prefer_single_quotes
    - lines_longer_than_80_chars
