name: eproperty
description: E-Property Mobile

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.14.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  auto_route: ^0.6.9
  build_context: ^3.0.0
  cached_network_image: ^2.5.1
  charts_flutter: ^0.10.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.0
  flutter_feather_icons: ^1.0.3
  flutter_form_builder:
    git: https://github.com/sportner/flutter_form_builder
  flutter_riverpod: ^0.13.1
  google_fonts: ^2.0.0
  google_nav_bar: ^5.0.3
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  image_picker: ^0.7.2+1
  intl: ^0.17.0
  logger: ^0.9.4
  percent_indicator: ^2.1.9+1

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: any
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  retrofit_generator:
    git:
      url: https://github.com/chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: generator

dependency_overrides:
  retrofit:
    git:
      url: https://github.com/chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: annotation

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # The following specifies the font used within the application.
  assets:
    - asset/image/

scripts:
  build: flutter pub run build_runner build
