name: main

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.23.x'
        channel: 'beta'
    - name: Enable Web
      run: flutter config --enable-web
    - name: Pub Get
      run: flutter pub get
    - name: Build Web
      run: flutter build web
    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./build/web
