name: web

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.23.x'
          channel: 'beta'
      - name: Configure Web Support
        run: flutter config --enable-web
      - name: Get Dependencies
        run: flutter pub get
      - name: Build Web
        run: flutter build web
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
          cname: eproperty.soyfou.xyz
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: pages
